function a = pLasso(Y,D,lambda)
  for i=1:size(Y,2)
      a(:,i) = SpaRSA(Y(:,i),D,lambda,...
                      'Monotone',1,...
                      'Debias',0,...
                      'StopCriterion',1,...
                      'ToleranceA',0.00000001, ...
                      'ToleranceD',0.000001, ...
                      'MaxiterA',1000,...
                      'Verbose',0);

    end
end
