function L = mdlsDefaultImages(sigma)
if ~exist('sigma','var')
  sigma=0;
end
if sigma <= 0 
  L = { ...
      'barbara',...
      'boat',...
      'mandrill',...
      'lena',...
      'peppers',...
      'goldhill' %,...
  %      'tools',...
  %      'man',...
  %      'bike',...
  %     'cats'
      };
else
  L = { ...
      sprintf('barbara_g%02d',sigma),...
      sprintf('boat_g%02d',sigma),...
      sprintf('mandrill_g%02d',sigma),...
      sprintf('lena_g%02d',sigma),...
      sprintf('peppers_g%02d',sigma),...
      sprintf('goldhill_g%02d',sigma) %,...
                                  %      sprintf('bike_g%02d',sigma) ,...
                                  %      sprintf('tools_g%02d',sigma),...
                                  %      sprintf('man_g%02d',sigma),...
                                  %      sprintf('cats_g%02d',sigma)
      };
end

end
