%
% function modelname=mdlsSaveModel(dirname,imgname,width,overlap,D,metric,lambda)
% 
function model=mdlsLoadModel(dirname,imgname,width,overlap,K,metric,lambda)
  suffix=mdlsModelSuffix(imgname,width,overlap,K,metric,lambda);
  modelname=sprintf('%s/model_%s.mat',dirname,suffix);
  fprintf('Loading model file %s\n',modelname);
  load(modelname);
  model=struct( ...
    'imgname', imgname, ...
    'width'  , width, ...
    'overlap', overlap , ...
    'D'      , D, ...
    'metric' , metric, ...
    'lambda' , lambda);
