function handle = doctool(s)
% function handle = doctool(s)
%
% $Id: doctool.m,v 1.6 2003-01-02 21:59:27-06 brinkman Exp $
% (c) 2002 Peter Brinkmann, brinkman@math.uiuc.edu
%
% doctool: Simple m-file for documentation fig-files generated by drawlayout
%
% doctool simply displays the figure from the fig file and displays the
% help text of the module that the user clicks on.
%
% Usage examle: doctool('guidoc')

% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

	if ischar(s)
		handle = openfig(s,'reuse');
		set(handle,'Color',get(0,'defaultUicontrolBackgroundColor'));
	else
		try
			eval(['helpwin ' get(s,'String') ';']);
		catch
			errordlg(lasterr);
		end
	end

